name: Weather Application

on: 
  workflow_dispatch: 
  push: 
    branches: 
      - main
      - 'feature/*'

jobs:
  Build-Deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download Gradle
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'gradle'
          distribution-version: '7.3.3'

      - name: Set up Gradle properties
        uses: SimonMarquis/ci-gradle-properties-action@v1
        with:
          path: gradle/gradle.properties  

